---
Name: silverware-events
---

# Configure Admin Extensions:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "silverware/events: admin/client/dist/styles/bundle.css"
  extra_requirements_javascript:
    - "silverware/events: admin/client/dist/js/bundle.js"
